[[plugins]]
package = "@netlify/plugin-nextjs"

[dev]
port = 8082
targetPort = 3001
autoLaunch = false

# Cache "/docs-static/_next/static/*" assets for 1 year
# [[headers]]
# for = "/docs-static/_next/static/*"
# [headers.values]
# "Cache-Control" = "max-age=31560000, immutable"


[[redirects]]
from = "/_next/*"
to = "/docs-static/_next/:splat"
status = 200
force = true
